Using directory facilitator
k1kli/hvac-with-agents pull request #18
Opened 2020-09-01 20:29 UTC by k1kli

Zawiera zmiany z #16 więc wcześniej trzeba tamto zmergować. Użycie directory facilitator zapewnia, że agenci do których wysyłamy wiadomości już są dostępni i nie musimy polegać na nazwie wejściowej agentów do ich rozpoznawania.
@DLZaan chyba lepiej będzie jak w room coordinatorze też to wprowadzisz, bo co podasz jako AID sąsiadów w argumentach wejściowych jak do utworzenia sąsiadów trzeba AID danego room coordinatora? Lepiej jako argument wejściowy podać chyba id pokoju danego sąsiada, a agent sam sobie go znajdzie, tak samo podać mu id jego pokoju jako argument wejściowy a on ustali swoją nazwę usługi oraz znajdzie na podstawie tego id swojego upkeepera.

2020-09-02 18:22 UTC, DLZaan requested changes
Całkowicie się zgadzam co do DF - nie pamiętam czy przypadkiem jak pisałem kod to jeszcze się nim nie posługiwaliśmy na zajęciach, i dlatego tak zrobiłem...
Dług techniczny trzeba spłacić, dodam DF dla RoomCoordinatora do tej gałęzi jak najszybciej.

2020-09-05 11:55 UTC, DLZaan commented
Please review my changes, from my side ready to pull.

2020-09-05 11:56 UTC, DLZaan approved these changes

2020-09-05 12:20 UTC, k1kli commented
I can't approve since i created the PR but looks good to me.

2020-09-05 12:20 UTC, merged